"""Deterministic evidence models for generic portal scraping."""

from scraper.models import (
    ActionCandidate,
    ActionKind,
    ActionRisk,
    ActionStatus,
    ArtifactReference,
    BrowserEvent,
    BrowserEventKind,
    CapturePolicy,
    CoverageReport,
    CrawlLimits,
    ElementSnapshot,
    FrameSnapshot,
    InteractionTransition,
    NetworkExchange,
    ScrapeRun,
    ScrapeRunStatus,
    StateSnapshot,
)

__all__ = [
    "ActionCandidate",
    "ActionKind",
    "ActionRisk",
    "ActionStatus",
    "ArtifactReference",
    "BrowserEvent",
    "BrowserEventKind",
    "CapturePolicy",
    "CoverageReport",
    "CrawlLimits",
    "ElementSnapshot",
    "FrameSnapshot",
    "InteractionTransition",
    "NetworkExchange",
    "ScrapeRun",
    "ScrapeRunStatus",
    "StateSnapshot",
]
